### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by falti** [hauleth/ecto_olap#10]
Hello Łukasz, I find this project very useful. Thanks a lot. I wonder if you still plan to maintain it?

**Comment by hauleth** [comment]
TBH I currently I do not see much value in maintaining it, as Ecto 3.0 has support for window functions natively and `ecto_function` allows defining custom functions easily. Do you have any functionalities in mind? Because of course I can maintain it, I just need to know what is needed.

**Comment by falti** [comment]
Thanks a lot for the quick response. I was not aware of `ecto_function` at all. Agreed, not much need for ecto_olap given these features in Ecto.
Closing the ticket.
